[package]
name = "lib_tower_defense"
version = "0.1.0"
edition = "2021"

[dependencies]
device_query = "1.1.2"
json = "0.12.4"
libc = "0.2.140"
regex = "1.7.1"
rmp-serde = "1.1.1"
sdl2 = "0.35.2"
serde = "1.0.158"
serde_derive = "1.0.158"
serde_test = "1.0"
thread = "0.1.0"
time = "0.3.20"

[dev-dependencies]
serde_test = { version = "1.0" }
